name: PR

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: '${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  docker-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag and SHA
        run: |
          CLEAN_TAG=$(echo "${{ github.event.pull_request.head.ref  }}"  | tr / -)
          echo "TAG=$CLEAN_TAG" >> $GITHUB_ENV
          echo "SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
      - name: Build
        run: >
          docker build -t onsdigital/eq-runner-mock-sds:$TAG .
      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Pushing to DockerHub with tag $TAG"
          docker push onsdigital/eq-runner-mock-sds:$TAG
