name: PR

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: '${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  lint-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.virtualenvs

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: make lint

      - name: Run pytest
        run: make test

